version: "3"

networks:
  internal:

volumes:
  storage-volume:

services:
  storage:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=manydecks
      - POSTGRES_PASSWORD=manydecks
    networks:
      - internal
    volumes:
      - storage-volume:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: "massivedecks/manydecks-server:latest"
    build: "../server"
    volumes:
      - ./config.json5:/md/config.json5
    depends_on:
      - storage
    environment:
      - NODE_ENV=production
    networks:
      - internal
    restart: unless-stopped

  client:
    image: "massivedecks/manydecks-client:latest"
    build: "../client"
    depends_on:
      - server
    ports:
      - "8082:8082"
    networks:
      - internal
    #volumes:
    #  - /path/to/custom/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
